### PR TITLE
Component Set support

### PR DESCRIPTION
**Pull request by julianclatro**
- Support to Insert new Instances from Component Sets.
- Moved types from 'figma-plugin-types' dependency to locally.

### CODE REVIEW

**Comment by julianclatro** [comment]
The idea of moving the types locally is to start a transition to the official types from figma (https://github.com/figma/plugin-typings)

**Comment by julianclatro** [comment]
https://user-images.githubusercontent.com/6716921/141315184-73841661-f792-4dcc-9328-e3c63ab66938.mov

**Comment by kawamurakazushi** [comment]
thanks, looks good! 

Just for curiosity, Is the frame icon appropriate for `Component Sets`  or should be the some other icon? 
CleanShot 2021-11-12 at 07 33 43@2x

**Comment by kawamurakazushi** [comment]
@julianclatro 
new versions is published!

thanks for the contribution.

**Comment by julianclatro** [comment]
Makes sense to be another icon, I will update it soon. Thank you!

**Pull request merged**
